const GUITARS = [
  {
    id: 1,
    name: 'Честер Bass',
    vendorCode: 'SO757575',
    type: 'electric',
    description: 'Вариант для настоящих профессионалов. Двенадцатиструнный инструмент оснащён карбоновыми струнами и корпусом из массива ели.',
    previewImg: 'img/content/guitar-1.jpg',
    stringCount: 7,
    rating: 4,
    price: 17500,
  },
  {
    id: 2,
    name: 'СURT Z30 Plus Acoustics',
    vendorCode: 'SO7568698',
    type: 'acustic',
    description: 'Вариант для настоящих профессионалов. Двенадцатиструнный инструмент оснащён карбоновыми струнами и корпусом из массива ели.',
    previewImg: 'img/content/guitar-2.jpg',
    stringCount: 6,
    rating: 9,
    price: 129500,
  },
  {
    id: 3,
    name: 'СURT Z30 Plus',
    vendorCode: 'SO7898989',
    type: 'electric',
    description: 'Вариант для настоящих профессионалов. Двенадцатиструнный инструмент оснащён карбоновыми струнами и корпусом из массива ели.',
    previewImg: 'img/content/guitar-3.jpg',
    stringCount: 7,
    rating: 4,
    price: 17500,
  },
  {
    id: 4,
    name: 'Честер Bass',
    vendorCode: 'SO757575',
    type: 'electric',
    description: 'Вариант для настоящих профессионалов. Двенадцатиструнный инструмент оснащён карбоновыми струнами и корпусом из массива ели.',
    previewImg: 'img/content/guitar-5.jpg',
    stringCount: 7,
    rating: 10,
    price: 15000,
  },
  {
    id: 5,
    name: 'СURT Z30 Acoustics',
    vendorCode: 'SO757575',
    type: 'acustic',
    description: 'Вариант для настоящих профессионалов. Двенадцатиструнный инструмент оснащён карбоновыми струнами и корпусом из массива ели.',
    previewImg: 'img/content/guitar-6.jpg',
    stringCount: 6,
    rating: 2,
    price: 200000,
  },

];

export {GUITARS};
